version: '3'

services:
  webapi:
    container_name: 'webapi-vs'
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 5001:80
    depends_on:
     - "postgres"
    networks:
      - backend-network
  
  postgres:
    container_name: 'postgres-vs'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata:

networks:
  backend-network:
    driver: bridge